CREATE OR REPLACE TYPE DIAK AS OBJECT (
    NEV VARCHAR2(30),
    SZEV INT,
    SZAK VARCHAR2(30)
);

CREATE TABLE DIAKOK (
    DID INT PRIMARY KEY,
    HALLGATO DIAK
);

INSERT INTO DIAKOK VALUES(1, DIAK('Tibi', 2000, 'Kereskedelem és marketing'));
INSERT INTO DIAKOK VALUES(2, DIAK('Bence', 2000, 'Kereskedelem és marketing'));
INSERT INTO DIAKOK VALUES(3, DIAK('Anett', 1996, 'Sportszervező'));

SELECT * FROM DIAKOK;

SELECT D.HALLGATO.NEV, DID FROM DIAKOK D;

UPDATE DIAKOK D SET D.HALLGATO.NEV = 'Tibor' WHERE D.DID = 1;
